### ISSUE TITLE
AHEasing Missing

### ISSUE THREAD

**Issue by dusave** [alexandre-g/FadingEdgesCollectionView#1]
It appears the AHEasing pod repo on github has been removed and is causing this package to fail on install.

**Comment by alexandre-g** [comment]
Hi, thanks for reporting. No idea where it went and seems to break quite a few pods :/
I've created a copy named `AHEasingPod` and created an issue on `HTGradientEasing` to resolve.
If they don't will create a copy of that too.
https://github.com/hoteltonight/HTGradientEasing/issues/3

If you need to use the pod before I suggest either getting the source or using with `HTGradientEasing` pod installed locally with `AHEasing` dependency changed to `AHEasingPod`.

**Comment by dusave** [comment]
Thanks for looking into that. No immediate need yet, but keep me posted when an updated version is available. Now I know why npm doesn’t want you unpublishing packages
